services:
  vagabond_postgres:
    image: postgres:16
    container_name: vagabond_postgres
    restart: always
    environment:
      - POSTGRES_USER=vagabond_dev
      - POSTGRES_PASSWORD=vagabond_dev
      - POSTGRES_DB=vagabond_dev
    ports:
      - 5432:5432
    expose:
      - "5432"

